name: easy_localization
description: Easy and Fast internationalizing and localization your Flutter Apps, this package simplify the internationalizing process using Json file.
author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization
issue_tracker: https://github.com/aissat/easy_localization/issues

version: 2.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  shared_preferences: ^0.5.6+3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  assets:
    - i18n/
