name: easy_localization
description: Easy and Fast internationalizing and localization your Flutter Apps, this package simplify the internationalizing process .
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization
issue_tracker: https://github.com/aissat/easy_localization/issues
# publish_to: none

version: 3.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.0 <3.0.0'
  intl: '>=0.17.0-0 <=0.18.1'
  args: ^2.3.1
  path: ^1.8.1
  easy_logger: ^0.0.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
