name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  csv: ^4.0.3
  yaml: ^2.2.0
  xml: ^3.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_test:
    sdk: flutter

